<script setup lang="ts">
import { ref } from 'vue';import { useVbenModal } from '@vben/common-ui';import { useVbenForm } from '#/adapter/form';import { message } from 'antdv-next';import { studioApi } from '#/api/studio';
const categoryOptions=ref<any[]>([]);
const emit=defineEmits(['success']);const file=ref<File | undefined>();const fileInput=ref<HTMLInputElement>();const [Form,formApi]=useVbenForm({layout:'vertical',showDefaultActions:false,schema:[{component:'Input',fieldName:'name',label:'工具名称',rules:'required'},{component:'Select',fieldName:'category',label:'分类',componentProps:{options:categoryOptions},rules:'required'},{component:'Input',fieldName:'tag',label:'标签'},{component:'Select',fieldName:'status',label:'推荐状态',defaultValue:'新品',componentProps:{options:[{label:'热门',value:'热门'},{label:'精选',value:'精选'},{label:'新品',value:'新品'}]}},{component:'Textarea',fieldName:'description',label:'描述'}]});
const [Modal,modalApi]=useVbenModal({async onConfirm(){const {valid}=await formApi.validate();if(!valid)return message.warning('请完整填写工具信息');const selectedFile=fileInput.value?.files?.[0] || file.value;if(!selectedFile){console.warn('zip file missing', {inputValue:fileInput.value?.value, fileCount:fileInput.value?.files?.length, cached:file.value?.name});return message.warning('请选择 ZIP 网页包')}modalApi.lock();try{const values=await formApi.getValues();const data=await studioApi.createToolWithUpload({...values,file:selectedFile});if(!data.id && !data.tool?.id)throw new Error('工具创建成功但未返回工具 ID');modalApi.close();emit('success')}catch(error){message.error(error instanceof Error?error.message:'工具创建失败')}finally{modalApi.lock(false)}},  onOpenChange:async(open)=>{if(open){formApi.reset();file.value=undefined;categoryOptions.value=(await studioApi.categories()).categories.map((name:string)=>({label:name,value:name}))}}});
function chooseFile(event:Event){const input=event.target as HTMLInputElement;file.value=input.files?.[0] || undefined}
defineExpose({modalApi});
</script>
<template><Modal title="新增工具"><Form/><div class="zip"><b>网页包</b><input ref="fileInput" type="file" accept=".zip,application/zip,application/x-zip-compressed" @change="chooseFile"><small>{{file?.name || 'ZIP 根目录必须包含 index.html，上传后系统自动生成访问地址'}}</small></div></Modal></template>
<style scoped>.zip{display:flex;align-items:center;gap:10px;margin:10px 0;color:#596f84;font-size:12px}.zip input{max-width:260px}.zip small{color:#91a0ad}</style>
